/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitQuitterRouteImport } from './routes/habit-quitter'
import { Route as GmailCallbackRouteImport } from './routes/gmail-callback'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlannerIndexRouteImport } from './routes/planner/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PlannerDateRouteImport } from './routes/planner/$date'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'
import { Route as AdminMotivationsRouteImport } from './routes/admin/motivations'
import { Route as AdminHabitsRouteImport } from './routes/admin/habits'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitQuitterRoute = HabitQuitterRouteImport.update({
  id: '/habit-quitter',
  path: '/habit-quitter',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailCallbackRoute = GmailCallbackRouteImport.update({
  id: '/gmail-callback',
  path: '/gmail-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlannerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlannerDateRoute = PlannerDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => PlannerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMotivationsRoute = AdminMotivationsRouteImport.update({
  id: '/motivations',
  path: '/motivations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHabitsRoute = AdminHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gmail-callback': typeof GmailCallbackRoute
  '/habit-quitter': typeof HabitQuitterRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/habits': typeof AdminHabitsRoute
  '/admin/motivations': typeof AdminMotivationsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/planner/$date': typeof PlannerDateRoute
  '/admin/': typeof AdminIndexRoute
  '/planner/': typeof PlannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gmail-callback': typeof GmailCallbackRoute
  '/habit-quitter': typeof HabitQuitterRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/habits': typeof AdminHabitsRoute
  '/admin/motivations': typeof AdminMotivationsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/planner/$date': typeof PlannerDateRoute
  '/admin': typeof AdminIndexRoute
  '/planner': typeof PlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gmail-callback': typeof GmailCallbackRoute
  '/habit-quitter': typeof HabitQuitterRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/habits': typeof AdminHabitsRoute
  '/admin/motivations': typeof AdminMotivationsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/planner/$date': typeof PlannerDateRoute
  '/admin/': typeof AdminIndexRoute
  '/planner/': typeof PlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/gmail-callback'
    | '/habit-quitter'
    | '/login'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/register'
    | '/admin/announcements'
    | '/admin/feedback'
    | '/admin/habits'
    | '/admin/motivations'
    | '/admin/rewards'
    | '/admin/users'
    | '/planner/$date'
    | '/admin/'
    | '/planner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/gmail-callback'
    | '/habit-quitter'
    | '/login'
    | '/notes'
    | '/profile'
    | '/register'
    | '/admin/announcements'
    | '/admin/feedback'
    | '/admin/habits'
    | '/admin/motivations'
    | '/admin/rewards'
    | '/admin/users'
    | '/planner/$date'
    | '/admin'
    | '/planner'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/gmail-callback'
    | '/habit-quitter'
    | '/login'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/register'
    | '/admin/announcements'
    | '/admin/feedback'
    | '/admin/habits'
    | '/admin/motivations'
    | '/admin/rewards'
    | '/admin/users'
    | '/planner/$date'
    | '/admin/'
    | '/planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GmailCallbackRoute: typeof GmailCallbackRoute
  HabitQuitterRoute: typeof HabitQuitterRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  PlannerRoute: typeof PlannerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habit-quitter': {
      id: '/habit-quitter'
      path: '/habit-quitter'
      fullPath: '/habit-quitter'
      preLoaderRoute: typeof HabitQuitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail-callback': {
      id: '/gmail-callback'
      path: '/gmail-callback'
      fullPath: '/gmail-callback'
      preLoaderRoute: typeof GmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/': {
      id: '/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof PlannerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/planner/$date': {
      id: '/planner/$date'
      path: '/$date'
      fullPath: '/planner/$date'
      preLoaderRoute: typeof PlannerDateRouteImport
      parentRoute: typeof PlannerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/motivations': {
      id: '/admin/motivations'
      path: '/motivations'
      fullPath: '/admin/motivations'
      preLoaderRoute: typeof AdminMotivationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/habits': {
      id: '/admin/habits'
      path: '/habits'
      fullPath: '/admin/habits'
      preLoaderRoute: typeof AdminHabitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminHabitsRoute: typeof AdminHabitsRoute
  AdminMotivationsRoute: typeof AdminMotivationsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminHabitsRoute: AdminHabitsRoute,
  AdminMotivationsRoute: AdminMotivationsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PlannerRouteChildren {
  PlannerDateRoute: typeof PlannerDateRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
}

const PlannerRouteChildren: PlannerRouteChildren = {
  PlannerDateRoute: PlannerDateRoute,
  PlannerIndexRoute: PlannerIndexRoute,
}

const PlannerRouteWithChildren =
  PlannerRoute._addFileChildren(PlannerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GmailCallbackRoute: GmailCallbackRoute,
  HabitQuitterRoute: HabitQuitterRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  PlannerRoute: PlannerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
